export const GET_ALL_DRIVERS = "GET_ALL_DRIVERS";
export const GET_DRIVERS_BY_NAME = "GET_DRIVERS_BY_NAME";
export const GET_ALL_TEAMS = "GET_ALL_TEAMS";
export const GET_DRIVERS_BY_TEAM = "GET_DRIVERS_BY_TEAM";
export const GET_DRIVERS_BY_TEAM_AND_SOURCE = "GET_DRIVERS_BY_TEAM_AND_SOURCE";
export const GET_DRIVERS_BY_SOURCE = "GET_DRIVERS_BY_SOURCE";
export const SORT_DRIVERS_BY_LAST_NAME = "SORT_DRIVERS_BY_LAST_NAME";
export const GET_DRIVER_BY_ID = "GET_DRIVER_BY_ID";
